services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

    